//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HM_Booking
    {
        public int BookingId { get; set; }
        public int RoomId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string Status { get; set; }
    
        public virtual HM_Room HM_Room { get; set; }
    }
}
