//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM.Data.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HMEntities : DbContext
    {
        public HMEntities()
            : base("name=HMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HM_Booking> HM_Booking { get; set; }
        public virtual DbSet<HM_Hotel> HM_Hotel { get; set; }
        public virtual DbSet<HM_RoomCategoryMaster> HM_RoomCategoryMaster { get; set; }
        public virtual DbSet<HM_Room> HM_Room { get; set; }
    }
}
